Nick several cards
plentycode/PlentyCode pull request #53
Opened 2021-09-25 06:47 UTC by Nicknddare

#46 
Cards created, Links added, Dynamic org. configured.
![imagen](https://user-images.githubusercontent.com/22461988/134761804-bb86fc75-7417-4371-b0f5-5cae24d77ec9.png)

2021-09-25 17:15 UTC, laura3arual requested changes
Please check the comments and fix them in another PR. Thank you. : )

2021-09-25 17:15 UTC, laura3arual commented on workspaces/Nicknddare/styles.css
> +  justify-content: space-around;
El atributo jusltify-content con el valor space-around trata de organizar los elementos para que ocupen todo el ancho del contenedor pero en este caso necesitamos que queden centrados como se ve en el figma por lo que puedes usar mejor el valor center.

2021-09-25 17:15 UTC, laura3arual commented on workspaces/Nicknddare/styles.css
> +    margin-bottom: 48px;
Teniendo en cuenta que cada card está dentro de un link, es mejor poner el margin en el link, ya que si dejas el margin en la card, se va a crear un espacio entre la parte de abajo del cards y la parte de abajo del link y esto significaría que puedes darle click a una parte vacía en la página, cómo se puede ver en esta imagen:
<img width="582" alt="Screen Shot 2021-09-25 at 12 11 14 PM" src="https://user-images.githubusercontent.com/4790488/134780313-d61c1d8d-0432-4e0e-b32f-c8064e62ba0f.png">

2021-09-26 00:21 UTC, Nicknddare commented on workspaces/Nicknddare/styles.css
> +  justify-content: space-around;
it works! code updated and working

2021-09-26 00:25 UTC, Nicknddare commented on workspaces/Nicknddare/styles.css
> +    margin-bottom: 48px;
Code updated! Nice tip. Thank u!
![imagen](https://user-images.githubusercontent.com/22461988/134789126-a513b219-2276-4535-bca6-40fa2fbe6c99.png)

2021-09-26 00:33 UTC, Nicknddare commented
Changes updated! It seems to be working now :)
![imagen](https://user-images.githubusercontent.com/22461988/134789215-2de558b7-6890-4397-a48d-ee5c1e707d8f.png)

2021-09-26 14:32 UTC, laura3arual approved these changes

2021-09-26 14:32 UTC, merged

2021-09-26 14:33 UTC, laura3arual commented
Perfect! Good job!